// <auto-generated />
using System;
using FlaggGaming.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlaggGaming.Migrations
{
    [DbContext(typeof(DatosContext))]
    [Migration("20240711224858_tabla juegoFlagg")]
    partial class tablajuegoFlagg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlaggGaming.Model.apiSteamListaJuegosTotal.ItemListaJuegoSteam", b =>
                {
                    b.Property<int>("appid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("appid"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.HasKey("appid");

                    b.ToTable("ItemListaJuegoSteam", (string)null);
                });

            modelBuilder.Entity("FlaggGaming.Model.juegoFlagg.FechaLanzamiento", b =>
                {
                    b.Property<Guid>("idFecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("fecha")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("proximamente")
                        .HasColumnType("BIT");

                    b.HasKey("idFecha");

                    b.ToTable("fechasDeLanzamiento", (string)null);
                });

            modelBuilder.Entity("FlaggGaming.Model.juegoFlagg.JuegoFlagg", b =>
                {
                    b.Property<Guid>("idFlagg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("contadorVistas")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("descripcionCorta")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("estudio")
                        .HasColumnType("varchar(max)");

                    b.Property<Guid?>("fechaLanzamientoidFecha")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("idJuegoTienda")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("idOferta")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("imagen")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("imagenMini")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("varchar(max)");

                    b.Property<Guid?>("ofertaidOferta")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("precio")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("requisitos")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("tienda")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("urlTienda")
                        .HasColumnType("varchar(max)");

                    b.HasKey("idFlagg");

                    b.HasIndex("fechaLanzamientoidFecha");

                    b.HasIndex("ofertaidOferta");

                    b.ToTable("juegos", (string)null);
                });

            modelBuilder.Entity("FlaggGaming.Model.juegoFlagg.Oferta", b =>
                {
                    b.Property<Guid>("idOferta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("discount_percent")
                        .HasColumnType("int");

                    b.Property<Guid>("idFlagg")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("idOferta");

                    b.ToTable("ofertas", (string)null);
                });

            modelBuilder.Entity("FlaggGaming.Model.juegoFlagg.JuegoFlagg", b =>
                {
                    b.HasOne("FlaggGaming.Model.juegoFlagg.FechaLanzamiento", "fechaLanzamiento")
                        .WithMany()
                        .HasForeignKey("fechaLanzamientoidFecha");

                    b.HasOne("FlaggGaming.Model.juegoFlagg.Oferta", "oferta")
                        .WithMany()
                        .HasForeignKey("ofertaidOferta");

                    b.Navigation("fechaLanzamiento");

                    b.Navigation("oferta");
                });
#pragma warning restore 612, 618
        }
    }
}
