@startuml
class JuegosEpicListaParcialService {
    + JuegosEpicListaParcialService(httpClientFactory:IHttpClientFactory)
    + JuegosEpicListaParcialService()
    + <<async>> getListaJuegosEpic() : Task<List<JuegoFlagg>>
}
@enduml
