@startuml
class JuegosListaTotalService {
    + JuegosListaTotalService()
    + JuegosListaTotalService(httpClientFactory:IHttpClientFactory)
    + <<async>> getListaJuegosSteam() : Task<ObjetoJsonListaJuegos>
}
@enduml
