@startuml
!include .\\Program.puml
!include .\\SingleOrArrayConverter.puml
!include .\\Controllers\IndexController.puml
!include .\\Controllers\UsuarioController.puml
!include .\\Entity\DatosContext.puml
!include .\\Migrations\20240315235345_inicial.puml
!include .\\Migrations\20240315235345_inicial.Designer.puml
!include .\\Migrations\20240316012225_actualizacion1.puml
!include .\\Migrations\20240316012225_actualizacion1.Designer.puml
!include .\\Migrations\20240711224858_tabla juegoFlagg.puml
!include .\\Migrations\20240711224858_tabla juegoFlagg.Designer.puml
!include .\\Migrations\20240925005029_inicialVersion5.puml
!include .\\Migrations\20240925005029_inicialVersion5.Designer.puml
!include .\\Migrations\20241010000252_inicialVersion6.puml
!include .\\Migrations\20241010000252_inicialVersion6.Designer.puml
!include .\\Migrations\DatosContextModelSnapshot.puml
!include .\\Model\Hardware.puml
!include .\\Model\IProducto.puml
!include .\\Model\Juego.puml
!include .\\Model\Procesador.puml
!include .\\Pages\Error.cshtml.puml
!include .\\Services\juegosIndexService.puml
!include .\\Services\TiendaService.puml
!include .\\Shared\Footer.razor.__projection.g.puml
!include .\\Shared\MainLayout.razor.__projection.g.puml
!include .\\Shared\NavMenu.razor.__projection.g.puml
!include .\\Model\apiEpic\Catalog.puml
!include .\\Model\apiEpic\Category.puml
!include .\\Model\apiEpic\Data.puml
!include .\\Model\apiEpic\Element.puml
!include .\\Model\apiEpic\Extensions.puml
!include .\\Model\apiEpic\FmtPrice.puml
!include .\\Model\apiEpic\KeyImage.puml
!include .\\Model\apiEpic\ObjetoJsonEpicGraphql.puml
!include .\\Model\apiEpic\Price.puml
!include .\\Model\apiEpic\SearchStore.puml
!include .\\Model\apiEpic\Seller.puml
!include .\\Model\apiEpic\TotalPrice.puml
!include .\\Model\apiSteamJuego\Achievements.puml
!include .\\Model\apiSteamJuego\Agcom.puml
!include .\\Model\apiSteamJuego\Cadpa.puml
!include .\\Model\apiSteamJuego\Category.puml
!include .\\Model\apiSteamJuego\ContentDescriptors.puml
!include .\\Model\apiSteamJuego\Dejus.puml
!include .\\Model\apiSteamJuego\Genre.puml
!include .\\Model\apiSteamJuego\Highlighted.puml
!include .\\Model\apiSteamJuego\JuegoSteam.puml
!include .\\Model\apiSteamJuego\JuegoSteamData.puml
!include .\\Model\apiSteamJuego\LinuxRequirements.puml
!include .\\Model\apiSteamJuego\MacRequirements.puml
!include .\\Model\apiSteamJuego\Movie.puml
!include .\\Model\apiSteamJuego\Mp4.puml
!include .\\Model\apiSteamJuego\Package.puml
!include .\\Model\apiSteamJuego\PackageGroups.puml
!include .\\Model\apiSteamJuego\PcRequirements.puml
!include .\\Model\apiSteamJuego\Platforms.puml
!include .\\Model\apiSteamJuego\PriceOverview.puml
!include .\\Model\apiSteamJuego\Ratings.puml
!include .\\Model\apiSteamJuego\Recommendations.puml
!include .\\Model\apiSteamJuego\ReleaseDate.puml
!include .\\Model\apiSteamJuego\Screenshot.puml
!include .\\Model\apiSteamJuego\SupportInfo.puml
!include .\\Model\apiSteamJuego\Usk.puml
!include .\\Model\apiSteamJuego\Webm.puml
!include .\\Model\apiSteamListaJuegosTotal\AppList.puml
!include .\\Model\apiSteamListaJuegosTotal\ItemListaJuegoSteam.puml
!include .\\Model\apiSteamListaJuegosTotal\ObjetoJsonListaJuegos.puml
!include .\\Model\juegoFlagg\FechaLanzamiento.puml
!include .\\Model\juegoFlagg\JuegoFlagg.puml
!include .\\Model\juegoFlagg\Oferta.puml
!include .\\Model\juegoFlagg\ReleaseDate.puml
!include .\\Model\objetosCalculos\DolarTarjeta.puml
!include .\\Model\scrapEpicJuego\JuegoEpic.puml
!include .\\Model\tienda\Categoria.puml
!include .\\Model\tienda\Producto.puml
!include .\\Model\tienda\Tienda.puml
!include .\\Model\usuarios\Usuario.puml
!include .\\Model\usuarios\UsuariosTienda.puml
!include .\\Model\usuarios\UsuarioTienda.puml
!include .\\Pages\componentesCargaDeProductos\RecuadroCargaDeProductos.razor.__projection.g.puml
!include .\\Pages\componentesIndex\Ofertas.razor.__projection.g.puml
!include .\\Pages\componentesSobreNosotros\Nosotros.razor.__projection.g.puml
!include .\\Services\CargaBaseDeDatos\CargaInfoJuegoEpicEnBAseDeDatos.puml
!include .\\Services\CargaBaseDeDatos\CargaInfoJuegoSteamEnBAseDeDatos.puml
!include .\\Services\CargaBaseDeDatos\CargaListaSteamEnBaseDeDatos.puml
!include .\\Services\EpicGameStoreNet\EpicGameStoreNetService.puml
!include .\\Services\ScrapEpic\RotadorDeUserAgentsForScrap.puml
!include .\\Services\ScrapEpic\ScrapWebEpicService.puml
!include .\\Services\ScrapEpic\UserAgent.puml
!include .\\Services\ServiciosAPIEpic\ConsultaApiEpic.puml
!include .\\Services\ServiciosAPIEpic\JuegoEpicService.puml
!include .\\Services\ServiciosAPIEpic\JuegosEpicListaParcialService.puml
!include .\\Services\ServiciosAPISteam\JuegosListaTotalService.puml
!include .\\Services\ServiciosAPISteam\JuegoSteamService.puml
!include .\\Services\ServiciosConTimer\TimerDescargaInfoJuegoSteam.puml
!include .\\Services\ServiciosConTimer\TimerDescargaListaTotalEpic.puml
!include .\\Services\ServiciosConTimer\TimerDescargaListaTotalSteam.puml
!include .\\Services\ServiciosParaCalculos\ServicioDolar.puml
!include .\\Services\ServiciosParaCalculos\ServicioIPC.puml
!include .\\Services\ServicioUsuario\ServicioUsuarioLogin.puml
!include .\\Model\apiEpic\apiEpicListaJuegosTotal\ItemListaJuegoEpic.puml
!include .\\Model\objetosCalculos\IPC\Identifiers.puml
!include .\\Model\objetosCalculos\IPC\InfoIPC.puml
!include .\\Model\objetosCalculos\IPC\Meta.puml
!include .\\Model\objetosCalculos\IPC\ParamsIPC.puml
!include .\\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\obj\Debug\net7.0\FlaggGaming.AssemblyInfo.puml
!include .\\obj\Debug\net7.0\FlaggGaming.GlobalUsings.g.puml
!include .\\obj\Debug\net7.0\FlaggGaming.RazorAssemblyInfo.puml
!include .\\obj\Release\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\obj\Release\net7.0\FlaggGaming.AssemblyInfo.puml
!include .\\obj\Release\net7.0\FlaggGaming.GlobalUsings.g.puml
!include .\\obj\Release\net7.0\FlaggGaming.RazorAssemblyInfo.puml
@enduml
